default:
  grid_size: 30
  color_values: 11
  n_steps: 2
  gamma: 0.99
  num_atoms: 51
  v_min: -40
  v_max: 2
  batch_size: 32
  replay_buffer_size: 1000000
  target_update_frequency: 5
  policy_lr: 0.001
  critic_lr: 0.001
  alpha: 0.2
  entropy_tau: 0.01
  clip_grad_norm: 10.0
  num_samples: 1000
  num_workers: 4
  device: cuda
  seed: 42

alternative:
  grid_size: 40
  color_values: 12
  n_steps: 3
  gamma: 0.98
  num_atoms: 52
  v_min: -50
  v_max: 3
  batch_size: 64
  replay_buffer_size: 2000000
  target_update_frequency: 10
  policy_lr: 0.01
  critic_lr: 0.01
  alpha: 0.3
  entropy_tau: 0.02
  clip_grad_norm: 20.0
  num_samples: 2000
  num_workers: 8
  device: cuda
  seed: 43