default: &default
  grid_size: 30
  color_values: 11
  n_steps: 10
  gamma: 0.99
  num_atoms:
    pixel_wise: 50
    n_reward: 50
    binary: 3
  v_min: 
    pixel_wise: 50
    n_reward: 50
    binary: 3
  v_max: 
    pixel_wise: 50
    n_reward: 50
    binary: 3
  batch_size: 32
  # Replay buffer
  replay_buffer_size: 1000000
  target_update_frequency: 5
  warmup_buffer_ratio: 0.1
  alpha: 0.6
  beta: 0.4
  # D4PG
  policy_lr: 0.0001
  critic_lr: 0.001
  tau: 0.001
  entropy_coef: 0.01
  entropy_coef_decay: 0.995
  clip_grad_norm: 10.0
  num_samples: 1000
  num_workers: 4
  device: cuda
  seed: 42

alternative:
  <<: *default
  grid_size: 40
  critic:
    num_atoms: 52